language: go
go:
    - 1.6
    - tip
matrix:
    allow_failures:
        - go: tip
install:
  - go get -u golang.org/x/lint/golint
before_script:
  - go get github.com/kisielk/errcheck

script:
  - make
